services:
  app:
    image: ghcr.io/doda2025-team3/app:${TAG_VERSION:-latest}
    container_name: app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      MODEL_HOST: "http://model-service:${MODEL_PORT:-8081}"
      APP_PORT: "${APP_PORT:-8080}"
    depends_on: 
      - model-service


  model-service:
    image: ghcr.io/doda2025-team3/model-service:${TAG_VERSION:-latest}
    container_name: model-service
    restart: unless-stopped
    ports:
      - "${MODEL_HOST:-8081}:8081"
    environment:
      MODEL_PORT: "${MODEL_PORT:-8081}"
    volumes:
      - ./output:/app/output
