services:
  app:
    image: ghcr.io/doda2025-team3/app:latest
    container_name: app
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      MODEL_HOST: "http://model-service:${MODEL_HOST:-8081}"
      APP_PORT: "${APP_PORT:-8080}"
    depends_on: 
      - model-service


  model-service:
    image: ghcr.io/doda2025-team3/model-service:latest
    container_name: model-service
    restart: always
    ports:
      - "${MODEL_HOST:-8081}:8081"
    environment:
      MODEL_HOST: "${MODEL_HOST:-8081}"
