services:
  app:
    image: ${APP_IMAGE}:${APP_VERSION:-latest}
    container_name: app
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      MODEL_HOST: "http://model-service:${MODEL_PORT:-8081}"
      SERVER_PORT: "${SERVER_PORT:-8080}"
    depends_on: 
      - model-service


  model-service:
    image: ${MODEL_IMAGE}:${MODEL_VERSION:-latest}
    container_name: model-service
    restart: unless-stopped
    ports:
      - "${MODEL_HOST:-8081}:8081"
    environment:
      MODEL_PORT: "${MODEL_PORT:-8081}"
      MODEL_PATH: "/models/model.joblib"
      MODEL_URL: "${MODEL_URL:-}"
    volumes:
      - ./models:/models
