app:
  image: "ghcr.io/doda2025-team3/app:latest"
  port: 8080

model:
  image: "ghcr.io/doda2025-team3/model-service:latest"
  port: 8081
  serviceName: "model-service"
  MODEL_URL: "https://github.com/doda2025-team3/model-service/releases/latest/download/model.joblib"

ingress:
  enabled: true
  host: "operation.local"
  className: "nginx"
  stableHost: "operation.local"
  canaryHost: "operation-canary.local"
  path: /

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  alertmanager:
    alertmanagerSpec:
      alertmanagerConfigSelector: {}
  grafana:
    enabled: true

monitoring:
  enabled: true
  alerts:
    email:
      enabled: true
      to: "carolynalcaraz2711@gmail.com"
      from: "alertmanager@example.com"
      require_tls: false
      smarthost: "mailhog:1025"
      username: ""
      password: ""
      passwordName: "alertmanager-secret-password"


config:
  logLevel: "LEVEL"
  extraConfig: |
    # Add optional config here

secret:
  enabled: true
  name: operation-credentials
  username: ""
  password: ""

sharedVolume:
  enabled: true
  hostPath: "/mnt/shared"
  mountPath: "/app/output"
