app:
  image: "ghcr.io/doda2025-team3/app:latest"
  port: 8080

model:
  image: "ghcr.io/doda2025-team3/model-service:latest"
  port: 8081
  serviceName: "model-service"
  MODEL_URL: "https://github.com/doda2025-team3/model-service/releases/latest/download/model.joblib"


ingress:
  enabled: true
  host: "operation.local"

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelector: {}
      podMonitorSelector: {}
  grafana:
    enabled: true

config:
  extraConfig: |
    # Add optional config here

secret:
  enabled: false
  username: "admin"
  password: "admin123"

sharedVolume:
  enabled: true
  hostPath: "/mnt/shared"
  mountPath: "/models"

istio:
  ingressGatewayLabel: ingressgateway