{{- if and .Values.modelService.enabled .Values.modelService.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-service-config
data:
  extra.conf: |
{{ .Values.modelService.config.extraConfig | indent 4 }}
{{- end }}
