apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: team3-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.app.ingress.hosts.stable | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: {{ .Values.app.service.port }}
    {{- if .Values.app.ingress.hosts.preview | quote }}
    - host: {{ .Values.app.ingress.hosts.preRelease | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: {{ .Values.app.service.port }}
    {{- end }}