{{- if .Values.modelService.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: model-service
  annotations:
    kubernetes.io/ingress.class: {{ .Values.modelService.ingress.className }}
spec:
  rules:
    - host: {{ .Values.modelService.ingress.hosts.stable | quote }}
      http:
        paths:
          - path: {{ .Values.modelService.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: model-service
                port:
                  number: {{ .Values.modelService.service.port }}
    - host: {{ .Values.modelService.ingress.hosts.preRelease | quote }}
      http:
        paths:
          - path: {{ .Values.modelService.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: model-service
                port:
                  number: {{ .Values.modelService.service.port }}
{{- end }}