{{- if and .Values.monitoring.enabled  .Values.monitoring.alerts.email.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.monitoring.alerts.email.passwordName }}
type: Opaque
stringData:
  password: {{ .Values.monitoring.alerts.email.password | quote }}
{{- end }}