{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Values.secret.name }}
type: Opaque
stringData:
  USERNAME: {{ .Values.secret.username | quote }}
  PASSWORD: {{ .Values.secret.password | quote }}
{{- end }}