apiVersion: networking.istio.io/v1beta1
kind: serviceEntry
metadata:
  name: {{ .Release.Name }}-httpbin-serviceentry
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - httpbin.org
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: tls
      protocol: TLS
  resolution: DNS