{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: operation-ingress
  # annotations:
  #   nginx.ingress.kubernetes.io/limit-rps: "5"
  #   nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
  #   nginx.ingress.kubernetes.io/limit-req-status-code: "429"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.stableHost }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
    - host: {{ .Values.ingress.canaryHost }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  number: 80
{{- end }}
