apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-entry
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - "*"
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: app
            subset: v1
            port:
              number: {{ .Values.app.port }}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 6aab31f (Open two frontend images.)
          weight: 100
=======
          weight: 70
>>>>>>> a6b987e (Frontend balancing.)
          headers:
            response:
              add:
                x-app-version: v1
<<<<<<< HEAD
=======
          weight: 90
>>>>>>> 4e46853 (Added the A4 traffic management part)
=======
>>>>>>> 6aab31f (Open two frontend images.)
        - destination:
            host: app
            subset: v2
            port:
              number: {{ .Values.app.port }}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 6aab31f (Open two frontend images.)
          weight: 0
=======
          weight: 30
>>>>>>> a6b987e (Frontend balancing.)
          headers:
            response:
              add:
                x-app-version: v2

<<<<<<< HEAD
=======
          weight: 10
>>>>>>> 4e46853 (Added the A4 traffic management part)
=======
>>>>>>> 6aab31f (Open two frontend images.)
