apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-service
    component: backend
  name: {{ .Values.model.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
    - name: http
      port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
