apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.model.serviceName }}
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
