apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
  template:
    metadata:
      labels:
        app: model-service
    spec:
      containers:
        - name: model-service
          image: {{ .Values.model.image }}
          ports:
            - containerPort: {{ .Values.model.port }}
          env:
            - name: MODEL_PORT
              value: "{{ .Values.model.port }}"
            - name: MODEL_PATH
              value: "/models/model.joblib"
            # - name: MODEL_URL
            #   value: "none"
          volumeMounts:
            - name: shared-volume
              mountPath: {{ .Values.sharedVolume.mountPath | quote }}
      volumes:
        - name: shared-volume
          hostPath:
            path: {{ .Values.sharedVolume.hostPath | quote }}
            type: DirectoryOrCreate
