apiVersion: v1
kind: Service
metadata:
  name: model-service
  labels:
    app: sms-checker
    component: backend
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
    - port: {{ .Values.model.port }}
      targetPort: {{ .Values.model.port }}
