apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: operation.rules
      rules:
        - alert: HighRequestRate
          expr: sum(rate(http_requests_total[1m])) > 15
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High request rate on {{ `{{ $labels.instance }}` }}"
            description: >
              Service recieved more than 15 HTTP requests/minute for >= 2 minutes.
