- import_playbook: general.yml

# - hosts: all
#   tasks:
#     - name: Ctrl components example
#       debug:
#         msg: "Install kube-apiserver, controller-manager, etcd, etc."

- name: Setup kubernetes
  hosts: ctrl
  become: true

  tasks: 
    # Step 13
    - name: Check if it is already initialised
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig

    - name: Initialize Kubernetes cluster with kubeadm
      ansible.builtin.command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --node-name=ctrl
        --pod-network-cidr=10.244.0.0/16
      when: not kubeconfig.stat.exists
      register: kubeadm_init
      changed_when: not kubeconfig.stat.exists

    # Step 14
    - name: Create .kube directory for vagrant user
      ansible.builtin.file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf to vagrant kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: true
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Copy kubeconfig to host machine
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /vagrant/kubeconfig
        remote_src: yes
        mode: '0600' #0644

    # Step 15
    # - name: Download Flannel manifest
    #   ansible.builtin.get_url:
    #     url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/Documentation/kube-flannel.yml
    #     dest: /tmp/kube-flannel.yml
    #     owner: vagrant
    #     group: vagrant
    #     mode: '0644'

    - name: Download Flannel manifest
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/flannel-io/flannel/v0.26.7/Documentation/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
        owner: root
        group: roor
        mode: '0644'

    # - name: Patch Flannel to use eth1 
    #   ansible.builtin.shell: |
    #     sed -i '/- --kube-subnet-mgr/a\        - --iface=eth1' /tmp/kube-flannel.yml

    - name: Patch Flannel to use eth1 
      ansible.builtin.lineinfile:
        path: /tmp/kube-flannel.yml
        insertafter: '^\s*- --kube-subnet-mgr\s*$'
        line: '        - --iface=eth1'
        state: present

    - name: Apply Flannel manifest
      ansible.builtin.command: kubectl apply -f /tmp/kube-flannel.yml
      become_user: vagrant
      register: flannel_apply
      changed_when: >
        ('created' in flannel_apply.stdout) or
        ('configured' in flannel_apply.stdout)

    # Step 16
    - name: Add Helm GPG key
      ansible.builtin.get_url:
        url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
        dest: /usr/share/keyrings/helm.asc
        mode: '0644'

    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/helm.asc] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main"
        state: present
        filename: helm-stable-debian

    - name: Install Helm
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: yes

    # Step 17
    - name: Check Helm plugins
      ansible.builtin.command: helm plugin list
      become_user: vagrant
      register: helm_plugins
      changed_when: yes

    - name: Install Helm plugin
      ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff
      become_user: vagrant
      when: "'diff' not in helm_plugins.stdout"
        