global:
  imagePullPolicy: IfNotPresent


app:
  enabled: true
  image:
    repository: ghcr.io/doda2025-team3/app
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    port: 8080
  env:
    SERVER_PORT: "8080"
    MODEL_HOST: "http://model-service:8081"  
  ingress:
    enabled: false
    className: nginx
    host: "app.local"
    # stable: "app-stable.local"
    # pre-release: "app-pre.local"
    path: "/" 


modelService:
  enabled: true
  image:
    repository: ghcr.io/doda2025-team3/model-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    port: 8081
  env:
    MODEL_PATH: "/models/model.joblib"
    MODEL_URL: ""  
  volume:
    hostPathEnabled: false
    hostPath: "/mnt/shared/models"  
    mountPath: "/models"
  ingress:
    enabled: false
    className: nginx
    hosts:
      stable: "model-stable.local"
      preRelease: "model-pre.local"
    path: "/" 
  config:
    extraConfig: |
      # Add optional config here
  secret:
    enabled: false
    username: "admin"
    password: "admin123"
