# Step 21 use fixed IP
controller:
  service:
    loadBalancerIP: 192.168.56.95
  ingressClassResource:
    name: nginx
    default: true
  extraArgs:
    default-ssl-certificate: "ingress-nginx/default-local-tls"