apiVersion: install.istio.io/v1
kind: IstioOperator
metadata:
  name: istio-operator
  namespace: istio-system
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  profile: istio-operator
  components:
    ingressGateways:
      - name: istio-ingressGateways
        enabled: true
        k8s:
          service:
            type: loadBalancerIP
            loadBalancerIP: 192.168.56.91